project:
  type: book

book:
  title: "Macfarlane Lab"
  author: "Gregory Macfarlane"
  date: "1/17/2023"
  chapters:
    - index.qmd
    - onboarding.qmd
    - workflow.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

