# Onboarding and Working

The process to onboard in my lab is:

1. I decide to hire you, and you agree to work for me.
2. You create an account on the Vikunja task management server for our lab at <https://vikunja.macfarlaneconsult.com>. You send me a message on Teams or email
    with your username.
3. I create an onboarding project on Vikunja for you. This project will have some tasks for me, and some tasks for you. Do each task as
   soon as possible. 

The tasks in your onboarding project will connect you with the following resources (beyond Vikunja)

  - **Workday** This is how you mark hours and work.
  - **Teams**  This is how you communicate with me and others on your research team.
  - **GitHub** This is how you collaborate with me and others on your research.
  

## Vikunja

I use Vikunja for task management. Vikunja is a web-based task management system
that allows us to track progress on projects, assign tasks to team members, and
log milestones. 

A couple of notes about using Vikunja in my lab:

  1. I am hosting this myself instead of paying lots of money for a commercial service. This means that we have a disk limit; please do not post images into discussions on Vikunja. Instead, you can host images on [imgur](https://imgur.com) and link to them in your Vikunja discussions.
  2. There is a limit on how many emails the system can send each month. This is why you should turn off your email notifications from vikunja. But you should bookmark the page or do other things so that you don't miss or forget tasks.

The Vikunja manual is here: <https://vikunja.io/help/> The manual contains lots of good tips on setting up filters, arranging tasks, and using Vikunja in general.

## Working 

When I hire you I will state expectations for a weekly commitment.
This is typically:

-   Undergraduate academic year: 5-10 hours per week
-   Undergraduate summer: 10-20 hours per week
-   Graduate student academic year: 10-20 hours per week
-   Graduate student Spring/Summer: 30+ hours per week

You may work whatever hours you choose, with the exception of the weekly lab meeting, any weekly project team meetings or project sponsor calls.  That said, I strongly recommend you schedule a regular time to dedicate to the research projects you are working on.  **The most effective students treat courses plus research as a full-time job**, arriving at the lab in the morning and working there on courses and research until they leave in the evening.  Other commitments might easily crowd out the time for your research if you do not prioritize the time.  Also, I want to pay you!  But I can't if you don't put in time.

I strongly recommend that students who work for me as a research assistant quit
any other research assistance, internship, or other external employment. If your employment
with me will not fill your time, speak with me about this situation.


### Wages

Students in my lab have their wages determined by skill and seniority, following the basic outlines of the [BYU hourly pay scale](https://hrs.byu.edu/hourly-pay-scale-and-job-codes).
Each semester I will evaluate student work and give raises as appropriate.

If you believe you merit a raise or there are needs in your family that might necessitate a higher wage, please speak to me.
I'll do what I can.

### Holidays

BYU has a policy that students who work on university holidays are paid overtime. If you intend to work hours
on a holiday ([days marked with `H` on the university calendar](https://academiccalendar.byu.edu)), you must clear it with me in advance.


## Teams

I use Teams for all lab-related communication.  Please install the Teams app on
your phone and your computer.  I expect you to respond to messages within a
reasonable amount of time, but I never expect you to respond while you are with
your families or other times when you are not working.

If you would like to reach me with a message, use Teams.

## GitHub

GitHub (and Git) is a tool for tracking changes to code and other text files. 
More details on using GitHub are available in @sec-workflow.

